In [3]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [13]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([5, 20, 14, 32, 22, 38])

In [11]:
print(x)

[[ 5]
 [15]
 [25]
 [35]
 [45]
 [55]]


In [6]:
print(y)

[ 5 20 14 32 22 38]


In [7]:
x.shape

(6, 1)

In [14]:
y.shape

(6,)

In [18]:
model = LinearRegression().fit(x,y)

In [20]:
model.score(x,y)

0.715875613747954

In [22]:
print('intercept:', model.intercept_)

intercept: 5.633333333333329


Intercept is a scalar while coef is a array

In [23]:
print('intercept:', model.coef_)

intercept: [0.54]


In [24]:
new_model = LinearRegression().fit(x,y.reshape((-1,1)))

In [25]:
print('intercept:', new_model.intercept_)
print('slope:', new_model.coef_)

intercept: [5.63333333]
slope: [[0.54]]


Predict responce 

In [29]:
y_pred =model.predict(x)
print('predicted response:',y_pred,sep = '\n')

predicted response:
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


In [33]:
y_pred = model.intercept_ + model.coef_*x 
y_pred

array([[ 8.33333333],
       [13.73333333],
       [19.13333333],
       [24.53333333],
       [29.93333333],
       [35.33333333]])

In [39]:
x_new = np.arange(5).reshape(-1,1)

In [40]:
y_new = model.predict(x_new)

In [41]:
y_new

array([5.63333333, 6.17333333, 6.71333333, 7.25333333, 7.79333333])

multiple Linear Regression with scikit-learn

In [50]:
x = [[0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]]
y = [4, 5, 20, 14, 32, 22, 38, 43]
x, y = np.array(x), np.array(y)

In [51]:
x

array([[ 0,  1],
       [ 5,  1],
       [15,  2],
       [25,  5],
       [35, 11],
       [45, 15],
       [55, 34],
       [60, 35]])

In [52]:
model = LinearRegression().fit(x,y)

In [55]:
print('coefficient of determination:', r_sq)

coefficient of determination: 0.8615939258756775


In [56]:
print('intercept:', model.intercept_)

intercept: 5.52257927519819


In [57]:
print('slope:', model.coef_)

slope: [0.44706965 0.25502548]


In [58]:
y_pred = model.predict(x)
print('predicted response:', y_pred, sep='\n')

predicted response:
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


In [107]:
y_pred = model.intercept_ + np.sum(model.coef_*x,axis = 1)
print('predicted response:', y_pred, sep='\n')

predicted response:
[ 9.03305493 16.05400623 23.07495753 30.09590883 37.11686014 44.13781144]


In [92]:
x_new = np.arange(10).reshape((-1,2))

In [93]:
x_new

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [94]:
y_new = model.predict(x_new)
print(y_new)

[ 5.77760476  7.18179502  8.58598528  9.99017554 11.3943658 ]


Polynomial Regression With scikit-learn

In [95]:
from sklearn.preprocessing import PolynomialFeatures

In [96]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([15, 11, 2, 8, 25, 32])

In [108]:
transformer = PolynomialFeatures(degree=2, include_bias=False)

In [109]:
transformer

PolynomialFeatures(include_bias=False)

In [113]:
x_ = PolynomialFeatures(degree=2, include_bias=False).fit_transform(x)

In [115]:
x_

array([[   5.,   25.],
       [  15.,  225.],
       [  25.,  625.],
       [  35., 1225.],
       [  45., 2025.],
       [  55., 3025.]])

In [122]:
model = LinearRegression().fit(x_,y)

In [123]:
r_sq = model.score(x_, y)

In [124]:
r_sq

0.8908516262498564

In [125]:
print('intercept:', model.intercept_)
print('coefficients:', model.coef_)

intercept: 21.372321428571425
coefficients: [-1.32357143  0.02839286]


In [129]:
x_1 = PolynomialFeatures(degree=2, include_bias=True).fit_transform(x)

In [130]:
x_1

array([[1.000e+00, 5.000e+00, 2.500e+01],
       [1.000e+00, 1.500e+01, 2.250e+02],
       [1.000e+00, 2.500e+01, 6.250e+02],
       [1.000e+00, 3.500e+01, 1.225e+03],
       [1.000e+00, 4.500e+01, 2.025e+03],
       [1.000e+00, 5.500e+01, 3.025e+03]])

In [131]:
model = LinearRegression(fit_intercept=False).fit(x_1, y)

In [134]:
r_sq = model.score(x_1, y)
print(r_sq)
print('intercept:', model.intercept_)
print('coefficients:', model.coef_)

0.8908516262498565
intercept: 0.0
coefficients: [21.37232143 -1.32357143  0.02839286]


In [135]:
y_pred = model.predict(x_1)

In [136]:
 print('predicted response:', y_pred, sep='\n')

predicted response:
[15.46428571  7.90714286  6.02857143  9.82857143 19.30714286 34.46428571]


several input variables

In [137]:
x = [[0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]]
y = [4, 5, 20, 14, 32, 22, 38, 43]
x, y = np.array(x), np.array(y)

In [139]:
x_ = PolynomialFeatures(degree=2, include_bias=False).fit_transform(x)

In [140]:
x_

array([[0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00, 1.000e+00],
       [5.000e+00, 1.000e+00, 2.500e+01, 5.000e+00, 1.000e+00],
       [1.500e+01, 2.000e+00, 2.250e+02, 3.000e+01, 4.000e+00],
       [2.500e+01, 5.000e+00, 6.250e+02, 1.250e+02, 2.500e+01],
       [3.500e+01, 1.100e+01, 1.225e+03, 3.850e+02, 1.210e+02],
       [4.500e+01, 1.500e+01, 2.025e+03, 6.750e+02, 2.250e+02],
       [5.500e+01, 3.400e+01, 3.025e+03, 1.870e+03, 1.156e+03],
       [6.000e+01, 3.500e+01, 3.600e+03, 2.100e+03, 1.225e+03]])

In [141]:
model = LinearRegression().fit(x_,y)

In [142]:
r_sq = model.score(x_,y)
intercept,coefficients = model.intercept_,model.coef_

In [143]:
y_pred = model.predict(x_)

In [144]:
print('coefficient of determination:', r_sq)

coefficient of determination: 0.9453701449127822


In [145]:
print('intercept:', intercept)

intercept: 0.8430556452395734


In [146]:
print('coefficients:', coefficients, sep='\n')

coefficients:
[ 2.44828275  0.16160353 -0.15259677  0.47928683 -0.4641851 ]


In [147]:
print('predicted response:', y_pred, sep='\n')

predicted response:
[ 0.54047408 11.36340283 16.07809622 15.79139    29.73858619 23.50834636
 39.05631386 41.92339046]
